apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: quickstart-es-http
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: quickstart-es-http
          servicePort: 9200
