apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: default
spec:
  encryptedData:
    BOILERPLATE_REDIS_PASS: AgBWFuZ54oK6mFrjiIE6tGWwXOb2rDX1V3slGbfVgKLbshzWMWcjaRBzO3xCMlXiS8fIw0JiiAbgM9puyyPTBykUhj7mQpOBC31IVUFabf6jIA5d4p4vfPsTJQpc/cXfEU/1nSnARqtJjpNsZGRBsRObJNbLA8Cs+495wuIgVfO9ykvYiSOUnUdcgcIzJmowNFjaY1K+3HDIhNQH4Y8GApa9hvTwzdJvt3iF3L1gDaN0UW97D87f0yGUgJvtmnosqb55StyVkqskPN+5fA2SWVw0/SOrMe2qKZ40sJ6jPU+P80Pi0UxJiYa95An4wLgvpGt7gCo+BF43TkZUQidnKIQswUubLw9oL7Y8lLuGYpFSD0Iq0AulLcbz4OXPiO6SGZJBLSSjKX8URKtOzw4u5lvwSbK50k01ckmLFonBHhIQ3jgXE1j46wjDQ+uZspeN6hmaQKQtKIpz6wZSrysRymL8LepXg79GHnTAoeOUbtIAOeWdj8hXLCzXieemyBPViX5Dk5wfpEhjSx7Tv+WfA8zRGBx9OZToU9F9H1N9Qm4Zk1CO6dV2SXXpisiv/E2oyh1WLX6hExJDahRBBSFhi4eA7yO3JL49ydFj0OeHYb1Hr9SO2S0IKtjpSU5mF0UGCWk/3TLCNbA29itej6lV2tF8X20E56jHNpqb8XlE35a+jdA+VG/eE+h56ekzlrtJpy9UXjDK1LKpZE7dXfqklpdYmEk=
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: default
    type: Opaque
