apiVersion: v1
kind: Service
metadata:
  labels:
    component: redis # cache/pub-sub
    type: ClusterIP
    name: redis
  name: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
