apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: boilerplate
spec:
  maxReplicas: 10
  minReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: boilerplate
