apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  POSTGRES_DB: "Ym9pbGVycGxhdGU=" # boilerplate
  POSTGRES_USER: "Ym9pbGVycGxhdGU=" # boilerplate
  POSTGRES_PASSWORD: "Ym9pbGVycGxhdGU=" # boilerplate
